version: '3'

services:
  redis:
    image: redis:6-alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  
  web:
    build: .
    volumes: 
      - .:/opt/app
    ports: 
      - 3000:3000
    command: bash -c "rails s -b 0.0.0.0 -p 3000"
    tty: true
    stdin_open: true
    depends_on:
      - redis

volumes:
  redis: